### PR TITLE
Improved UI

### PR DESCRIPTION
**Pull request by TechSpiritSS**
Issue #61 

Changes Made:

- Change of Font to Slabo
- Multiple Cards on Large Screen.

image

- Added Country Flag
-  Stars ★
- Cleaner Buttons
- Aligned Buttons in single line for large screens
- Added Contests Count
- Pointers on Hovers

image

- Cleaner Mobile View

image

- Minor UI Bug Fixings

### CODE REVIEW

**Comment by yashchaudhari008** [comment]
It doesn't feel good! 
If you can check new material design's documentation and make changes following the documentation, it would be great..
Also the font seems a little odd.

**Review by yashchaudhari008 — CHANGES_REQUESTED** [review]
It's not improving UI/UX experience

**Comment by TechSpiritSS** [comment]
There are UI changes but it's fine, if you aren't finding them good enough for PR.

**Comment by TechSpiritSS** [comment]
@yashchaudhari008 if you don't mind, can I use your API in my project? 
[Link](https://techspiritss.github.io/Terminal-Portfolio/)

**Comment by yashchaudhari008** [comment]
> @yashchaudhari008 if you don't mind, can I use your API in my project? 
> [Link](https://techspiritss.github.io/Terminal-Portfolio/)

Sure Bro✌️, just add original repo link showing API page.

**Comment by TechSpiritSS** [comment]
Thanks :)

**Pull request closed without merging**
