### PR TITLE
Replace delete button with a cross in user card

### LINKED ISSUE #2: UI Improvement: Add cross button(replacing delete button) and minimize few card details.
Having profiles saved in a local memory is alright since it prevents typing the same handles, again and again, every time open this tool, but I guess they do not get cleared from storage even when the delete button is clicked, due to which they get temporarily removed from the page, but get reappeared sometimes as the page is reloaded or visited again. This issue has been observed with multiple additions and deletions. I believe this is an issue and needs to be fixed. 

Also, for the current temporary removal functionality of the Delete button, a cross button at the top-right could be considered that could either remove the card HTML straightaway or could also just set its visibility to hidden or display to none. Along with it, can we also have a card minimize button alongside? Any other suggestions are also welcome.

### PR DESCRIPTION
**Pull request by Git-Harshit**
This Pull Request resolves #2 and #14 issues

The delete button is replaced by a cross mark placed at the top-right of every card using CSS, and 'Highest Rank' heading is replaced with 'Highest Rating' title.

Cards with cross button:
_C__Users_Devil's%20Lair_Desktop_Temp_Open%20Source_Codechef_Cards_index html

Cross button on hover:
_C__Users_Devil's%20Lair_Desktop_Temp_Open%20Source_Codechef_Cards_index html (2)

Please have a look, and let me know below if any changes are needed in it.

### CODE REVIEW

**Comment by Git-Harshit** [comment]
Yes, I guess it was a lot smaller before, so I have set it around username `<div>`. How is the cross button now? 

_C__Users_Devil's%20Lair_Desktop_Temp_Open%20Source_Codechef_Cards_index html

And for the minimize card option, let me try including a dropdown option before the username in the same division.

**Comment by Git-Harshit** [comment]
How does it seem now? Have a look:

Expanded Cards (default for now)

_C__Users_Devil's%20Lair_Desktop_Temp_Open%20Source_Codechef_Cards_index html (1)

Collapsed Cards 

Codechef_Cards_index


Have a look, and let me know if any further changes are needed

**Comment by Git-Harshit** [comment]
> Hey @Git-Harshit, I am expecting some like:- image And this will be default state.
> 
> * Cross-button on hover will just change color to white, no other styling.
> * After elements are expanded (i.e extra details are shown) "Show Details" show become "Hide Details" (placed at bottom)

It looks good! In case you already have it implemented, please go ahead and merge it directly into your code, because there's no advantage in repeating the same work. I will close the PR and look for some other contributions to it.

**Comment by yashchaudhari008** [comment]
> > Also there is no way to minimize more details
> 
> Yes, other than page refresh that gets cards back to their minimized state. Would you want me to set 'More Details' as a toggle? If so, just react with a thumbs up 👍🏻 in this comment and I'll try to set it that way instead of current one.

I need suggestion from you, is current layout good? or first app layout was good.

**Pull request merged**
