### PR TITLE
#57 - Added button to display and hide more details section.

### PR DESCRIPTION
**Pull request by NitinNair89**
Please review and suggest changes. Also guide me to responsively make the toggle function. I have added button to show/hide content for now.

### CODE REVIEW

**Comment by yashchaudhari008** [comment]
Please check, your commit has too many indentation changes

**Comment by NitinNair89** [comment]
> Please check, your commit has too many indentation changes

Yes, it got auto indented using default settings of VS Code. Do you have a Prettier config file which I can use?

**Comment by yashchaudhari008** [comment]
Use the Prettier mentioned in README.md (default settings will work).

**Comment by NitinNair89** [comment]
Hi @yashchaudhari008 
I have updated indentation to `Tab size: 4`, previously it was `Tab size: 2`.
Please review and let me know if any changes required.

**Comment by yashchaudhari008** [comment]
Hey , I don't know what's the problem but still indentation changes are there even they are fixed!!!. Something is wierd in this PR!
Can you create new branch from current main and just add your code without any prettification?

**Comment by yashchaudhari008** [comment]
Is this PR for hacktoberfest?

**Comment by NitinNair89** [comment]
> Is this PR for hacktoberfest?
> 
> Your current approach hide details on big screen too! They should be only hidden on mobile displays

Yes it is for hacktoberfest. But it is also because I want to get exposure in ReactJS. 🙂 
If I hide it via CSS, then button functionality does not work. I'm quite new to ReactJS and want to get to know more on this. Any help is appreciated.

**Comment by NitinNair89** [comment]
This is my Prettier config right now:
```
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 4,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "d:\\Work\\Codechef_Cards\\src\\Card.css",
  "parser": "css"
}
```

**Comment by yashchaudhari008** [comment]
Use
`tabWidth: 2`
`useTabs: true`

**Comment by yashchaudhari008** [comment]
> > Is this PR for hacktoberfest?
> > Your current approach hide details on big screen too! They should be only hidden on mobile displays
> 
> Yes it is for hacktoberfest. But it is also because I want to get exposure in ReactJS. 🙂 If I hide it via CSS, then button functionality does not work. I'm quite new to ReactJS and want to get to know more on this. Any help is appreciated.

- I guess you can check if the mobile device or not and save true/false in state.
- Then do conditional rendering

**Comment by NitinNair89** [comment]
> > > Is this PR for hacktoberfest?
> > > Your current approach hide details on big screen too! They should be only hidden on mobile displays
> > 
> > 
> > Yes it is for hacktoberfest. But it is also because I want to get exposure in ReactJS. 🙂 If I hide it via CSS, then button functionality does not work. I'm quite new to ReactJS and want to get to know more on this. Any help is appreciated.
> 
> * I guess you can check if the mobile device or not and save true/false in state.
> * Then do conditional rendering

Sure, thank you. Let me try it. 🙂

**Comment by yashchaudhari008** [comment]
@NitinNair89 Any Updates or should I close the PR?

**Comment by NitinNair89** [comment]
> @NitinNair89 Any Updates or should I close the PR?

Hi,
Please give me few more days, because I got caught up in work deliveries. I will try to finish this in the upcoming weekend.

I hope that's okay with you. Otherwise you can close this PR and I can request a new PR.

**Comment by yashchaudhari008** [comment]
No issues, I just wanted to know that you are working else someone could look into issue.

> > @NitinNair89 Any Updates or should I close the PR?
> 
> Hi, Please give me few more days, because I got caught up in work deliveries. I will try to finish this in the upcoming weekend.
> 
> I hope that's okay with you. Otherwise you can close this PR and I can request a new PR.

**Comment by NitinNair89** [comment]
Sure, if someone wants to work and would deliver it before your deadline then you can assign them. But I would still work (without PR in that case) because I basically want to learn React :)

**Comment by NitinNair89** [comment]
Hi @yashchaudhari008 
Please review latest commit. I have updated Prettier config as per your suggestions:
```{
  "filepath": "d:\\Work\\Codechef_Cards\\src\\Card.js",
  "parser": "babel",
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": true,
  "vueIndentScriptAndStyle": false
}

**Review by yashchaudhari008 — APPROVED** [review]

**Comment by yashchaudhari008** [comment]
Thanks for contributing.👍

**Comment by NitinNair89** [comment]
> Thanks for contributing.👍

Thank you, it was a good learning experience for me. If there are other issues or projects that I can work on, please do let me know 🙂

**Pull request merged**
