### PR TITLE
#1 UI Improvement: Add Toggle to Show/Hide Menu

### PR DESCRIPTION
**Pull request by Nevilkumar**
Screenshot (515)
Screenshot (516)

@yashchaudhari008 Let me know if you don't like the UI because I had made some changes to it. If you like it then please merge my PR.
Thanks.

### CODE REVIEW

**Comment by yashchaudhari008** [comment]
Sorry for requesting so many changes, but I want to keep project easy to understand and simple. Hope you will understand.

**Comment by Nevilkumar** [comment]
Screenshot (518)
Screenshot (517)

@yashchaudhari008 whether this looks good to you?

**Comment by Nevilkumar** [comment]
@yashchaudhari008 I had tried to make the changes but I don't know how to make a hide class and hide the data, so I had not made that change. Please merge my PR.
Thanks.

**Comment by yashchaudhari008** [comment]
> @yashchaudhari008 I had tried to make the changes but I don't know how to make a hide class and hide the data, so I had not made that change. Please merge my PR. Thanks.

No issues, I will refactor the code
Thanks for contributing.

**Pull request merged**
